CREATE TABLE USER_ONE (
    USER_ID varchar2(6) primary key, 
    USER_NAME varchar2(10)
);

INSERT INTO USER_ONE (USER_ID, USER_NAME) VALUES ('101', 'RONALDO');
INSERT INTO USER_ONE (USER_ID, USER_NAME) VALUES ('102', 'MESSI');

desc USER_ONE;

select * from USER_ONE;

CREATE TABLE USERONE (
    USER_ID varchar2(6) primary key, 
    USER_NAME varchar2(10)
);

INSERT INTO USERONE (USER_ID, USER_NAME) VALUES ('101', 'RONALDO');
INSERT INTO USERONE (USER_ID, USER_NAME) VALUES ('102', 'MESSI');

SELECT * FROM USERONE;

commit;
